title: Jennifer Lotz
email: lotz@stsci.edu
description: > # this means to ignore newlines until "baseurl:"
 life, the universe, and everything.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Jennifer Lotz # add your name
author-pic: jenlotz.jpg
about-author: My name is Jennifer Lotz.  I'm an astronomer at the Space Telescope Science Institute. With the Hubble Space Telescope, I hunt for the first galaxies in the universe and watch galaxies collide. 

# Contact links
email: lotz@stsci.edu # Add your Email address
phone: 410 338 4467 # Add your Phone number
website: jenlotz.github.io # Add your website, do not add http://
#linkedin: # Add your Linkedin handle
github: jenlotz # Add your Github handle
orcid: 0000-0003-3130-5643
gscholar: ZcYscoEAAAAJ
cv: /assets/pdfs/lotz_cv2017b.pdf

# Newsletter
#mailchimp: # Add your MailChimp form identifier.

# Disqus
#discus_identifier: mr-brown # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
